### ISSUE TITLE
Introduce CreateTable functionality for creating tables through UI

### ISSUE THREAD

**Issue by harshavardhana** [minio/minsql#25]

**Comment by harshavardhana** [comment]
Let's not worry about authentication, for now, @kanagarajkm but propose an API based on the `config.toml` datastore and table.

**Comment by kanagarajkm** [comment]
@harshavardhana are we going to allow adding new datastores through UI/API? 

API for CreateTable could be
```
POST /tables/
{"name": "tablename", "datastores": ["play", "myminio"]}
```

**Comment by harshavardhana** [comment]
yes we are going to @kanagarajkm we can add add such an API
