### ISSUE TITLE
Explore text classifications for objects

### ISSUE THREAD

**Issue by deekoder** [minio/minsql#7]

**Comment by harshavardhana** [comment]
This is probably slated for future this requires MinIO server side changes as well.

**Comment by fwessels** [comment]
Here is a pointer for fast grepping to explore: https://blog.burntsushi.net/ripgrep/#anatomy-of-a-grep

**Comment by ghost** [comment]
@harshavardhana would this involve indexing the data at all ?

**Comment by harshavardhana** [comment]
@gedw99 no the idea is to provide text matching as a special function in either select syntax or an entirely new style doing `grep` .

It will still be doing it row wise, with no indexing of data.
